name: demo

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Publish Blogifier
      run: dotnet publish -c Release -o release --nologo
